# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     - name: Clone repository
       uses: actions/checkout@v2 #v3
     - name: Use Node.js 18.x
       uses: actions/setup-node@v1 #v3
       with:
          node-version: 18.x
     - name: Install dependencies
       run: npm install
       working-directory: 'reacttest'
     - name: Test
       run: npm test
       working-directory: 'reacttest'
       env:
        CI: true
     - name: Generate build
       run: npm run build
       working-directory: 'reacttest'
# Share artifact inside workflow
     - name: Share artifact inside workflow
       uses: actions/upload-artifact@v1
       with:
           name: react-github-actions-build
           path: build
